spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expedientes_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      spring:
      logging:
        level:
          root: INFO
        log:
          color:
            enabled: true

exp:
  openapi:
    url: "http://localhost:8080"
    description: "API for managing gym operations, clients, routines, and nutrition plans."
    contact:
      name: "Santiago Agustín Paniagua"
      email: "paniaguasanty10@gmail.com"
      url: "https://github.com/PaniaguaSanty"
    title: "Gym Management API"
    version: "1.0"