spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/expedientes_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always # permite ver el log como colores
server:
  port: 8080
logging:
  level:
    root: info # permite ver los logs de consola

exp:
  openapi:
    url: "http://localhost:8080"
    description: "API for managing Expedient operations for the Ministerio de Educacion of Posadas Misiones, Argentina."
    contact:
      name: "Santiago Agustín Paniagua & Facundo Emanuel Pedrozo"
      email: "paniaguasanty10@gmail.com"
      url: "https://github.com/PaniaguaSanty"
    title: "Expedients Management API"
    version: "1.0"
